name: Docker Image CI - Continuous

on:
  push:
    paths:
    - 'tags/continuous/**'
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 14 * * *'
  workflow_dispatch:

env:
  IMAGE_NAME: gama
  VERSION: continuous

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file ./tags/${{ env.VERSION }}/Dockerfile --tag gamaplatform/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Publish in Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker push gamaplatform/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        docker logout