name: Docker Image CI - 1.8.1

on:
  push:
    paths:
    - 'tags/1.8.1/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file ./tags/1.8.1/Dockerfile --tag gamaplatform/gama:latest

    - name: Log in Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Push new container to Docker Hub
      run: docker push gamaplatform/gama:latest