name: Docker Image CI - Latest

on:
  push:
    paths:
    - 'tags/1.8.1/**'
  schedule:
    - cron: "0 0 1 */5 *" # Prevent Docker Hub stale
  workflow_dispatch:

env:
  IMAGE_NAME: gama
  VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Build the Docker image
      run: docker build . --file ./tags/1.8.1/Dockerfile --tag gamaplatform/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

    - name: Publish in Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
        docker push gamaplatform/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        docker logout
